
export const columns = [
  { field: "id", headerName: "ID", width: 33 },
  { field: "registrarId", headerName: "Registrar ID" },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    cellClassName: "name-column--cell",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "left",
    align: "left",
    flex: 1,
  },
  {
    field: "phone",
    headerName: "Phone Number",
    flex: 1,
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
  },
];

export const rows = [
  
  {
    id: 1,
    name: "Mohammed",
    email: "Mohammed@gmail.com",
    age: 35,
    phone: "(971)121-5454",
    address: "Abu Dhabi",
    city: "Abu Dhabi",
    zipCode: "0000",
    registrarId: 123512,
  },
  {
    id: 2,
    name: "Yamen",
    email: "Yamen@gmail.com",
    age: 42,
    phone: "(971)314-2288",
    address: "Dubai",
    city: "Dubai",
    zipCode: "0000",
    registrarId: 123512,
  },
  {
    id: 3,
    name: "Ahmed",
    email: "Ahmed@gmail.com",
    age: 45,
    phone: "(971)982-6739",
    address: "Dubai",
    city: "Dubai",
    zipCode: "0000",
    registrarId: 4132513,
  },
  {
    id: 4,
    name: "Mohammed",
    email: "Mohammed@gmail.com",
    age: 35,
    phone: "(971)121-5454",
    address: "Abu Dhabi",
    city: "Abu Dhabi",
    zipCode: "0000",
    registrarId: 123512,
  },
  {
    id: 5,
    name: "Yamen",
    email: "Yamen@gmail.com",
    age: 42,
    phone: "(971)314-2288",
    address: "Dubai",
    city: "Dubai",
    zipCode: "0000",
    registrarId: 123512,
  },
  {
    id: 6,
    name: "Ahmed",
    email: "Ahmed@gmail.com",
    age: 45,
    phone: "(971)982-6739",
    address: "Dubai",
    city: "Dubai",
    zipCode: "0000",
    registrarId: 4132513,
  },
  {
    id: 7,
    name: "Mohammed",
    email: "Mohammed@gmail.com",
    age: 35,
    phone: "(971)121-5454",
    address: "Abu Dhabi",
    city: "Abu Dhabi",
    zipCode: "0000",
    registrarId: 123512,
  },
  {
    id: 8,
    name: "Yamen",
    email: "Yamen@gmail.com",
    age: 42,
    phone: "(971)314-2288",
    address: "Dubai",
    city: "Dubai",
    zipCode: "0000",
    registrarId: 123512,
  },
  {
    id: 9,
    name: "Ahmed",
    email: "Ahmed@gmail.com",
    age: 45,
    phone: "(971)982-6739",
    address: "Dubai",
    city: "Dubai",
    zipCode: "0000",
    registrarId: 4132513,
  },

  {
    id: 10,
    name: "Ahmed",
    email: "Ahmed@gmail.com",
    age: 45,
    phone: "(971)982-6739",
    address: "Dubai",
    city: "Dubai",
    zipCode: "0000",
    registrarId: 4132513,
  },
  {
    id: 11,
    name: "Mohammed",
    email: "Mohammed@gmail.com",
    age: 35,
    phone: "(971)121-5454",
    address: "Abu Dhabi",
    city: "Abu Dhabi",
    zipCode: "0000",
    registrarId: 123512,
  }


];

