

export const rows = [
  {
    id: 1,
    name: "Mohammed",
    email: "Mohammed@gmail.com",
    age: 35,
    phone: "(971)121-5454",
    access: "Admin",
  },
  {
    id: 2,
    name: "Ahmed",
    email: "Ahmed@gmail.com",
    age: 42,
    phone: "(971)314-2288",
    access: "Admin",
  },
  {
    id: 3,
    name: "Yamen",
    email: "Yamen@gmail.com",
    age: 45,
    phone: "(971)982-6739",
    access: "Admin",
  },
  {
    id: 4,
    name: "Amr",
    email: "Amr@gmail.com",
    age: 16,
    phone: "(971)425-6742",
    access: "Manager",
  },
  {
    id: 5,
    name: "Eman",
    email: "Eman@gmail.com",
    age: 31,
    phone: "(971)445-1189",
    access: "Manager",
  },
  {
    id: 6,
    name: "Aslam",
    email: "Aslam@gmail.com",
    age: 150,
    phone: "(971)545-6483",
    access: "User",
  },
  {
    id: 7,
    name: "john",
    email: "John@gmail.com",
    age: 44,
    phone: "(971)124-0123",
    access: "User",
  },
  {
    id: 8,
    name: "Noorah",
    email: "Noorah@gmail.com",
    age: 36,
    phone: "(971)444-5555",
    access: "User",
  },
  {
    id: 9,
    name: "Hesham",
    email: "Hesham@gmail.com",
    age: 65,
    phone: "(971)555-6239",
    access: "User",
  },
];

